name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Show cluster info
      run: kubectl get pods -A

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -t devopshint/node-app:latest .
        docker images

    - name: Deploy to minikube
      run: |
        kubectl apply -f k8s-node-app.yaml

    - name: Wait for pod to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=120s

    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url

    - name: Debug pod logs (if failure)
      if: failure()
      run: |
        echo "=== PODS ==="
        kubectl get pods -o wide
        echo "=== LOGS ==="
        kubectl logs -l app=nodejs-app || true
